# Generated by Django 3.1.5 on 2021-01-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='登陆密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing_user.userinfo')),
            ],
            options={
                'verbose_name': '用户登陆token',
                'db_table': 'user_token',
            },
        ),
    ]
