# Generated by Django 2.1.3 on 2021-01-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_runner', '0003_mock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mock',
            name='description',
        ),
    ]
