# Generated by Django 2.1.3 on 2021-01-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_runner', '0004_remove_mock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='description',
            field=models.CharField(max_length=1024, null=True, verbose_name='Mock接口描述'),
        ),
    ]
